### PR TITLE
Test Ruby 2.3 on Travis CI

### PR DESCRIPTION
**Pull request by walro**

### CODE REVIEW

**Comment by roback** [comment]
Tests passed :)

:shipit:

**Comment by walro** [comment]
I ponder if we should add 2.3 to the README without having _actually_ tested, but we trust in our tests, right? :)

**Comment by roback** [comment]
> but we trust in our tests, right? :)

Yes, of course :)

**Comment by jage** [comment]
> I ponder if we should add 2.3 to the README without having actually tested, but we trust in our tests, right? :)

I've used it with Ruby 2.3, works like charm! :-)

**Pull request merged**
